name: web
description: An Nyxx example web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Benny Jacobs <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  nyxx:
    path: ../..
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
