name: pull request unit tests

on: [pull_request]

jobs:
  test-nyxx:
    name: Test main nyxx package
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx
        run: dart analyze

      - name: Unit tests
        working-directory: ./nyxx
        run: dart test test/unit.dart

  test-commander:
    name: Tests commander package
    needs: [test-nyxx]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx_commander
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx_commander
        run: dart analyze

  test-extensions:
    name: Tests extensions package
    needs: [test-nyxx]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
     - name: Cache
       uses: actions/cache@v2
       with:
        path: ~/.pub_cache
        key: ${{ runner.os }}

     - name: Setup Dart Action
       uses: cedx/setup-dart@v2.3.0
       with:
        release-channel: stable

     - name: Checkout
       uses: actions/checkout@v2.3.4

     - name: Install dependencies
       working-directory: ./nyxx_extensions
       run: dart pub get

     - name: Analyze project source
       working-directory: ./nyxx_extensions
       run: dart analyze

     - name: Unit tests
       working-directory: ./nyxx_extensions
       run: dart test test/extensions-tests.dart

  test-interactions:
    name: Tests interactions package
    needs: [test-nyxx]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
          release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx_interactions
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx_interactions
        run: dart analyze

      - name: Unit tests
        working-directory: ./nyxx_interactions
        run: dart test test/unit.dart
